server:
  port: 5555
  servlet:
    context-path: /uaa
spring:
  application:
    name: service-auth
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zuul-auth?useUnicode=true&characterEncoding=utf-8&characterSetResults=utf-8
    username: root
    password: root
    druid:
          driver-class-name: com.mysql.jdbc.Driver
  redis:
      host: 127.0.0.1
      port: 6379
      password: T4SSqQubVc32g
      database: 7

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
logging:
  config: classpath:logback.xml
  level:
    org:
      springframework:
        web: info
###feign 默认关闭熔断，请看HystrixFeignConfiguration
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1