eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
   #prefix: /api #为zuul设置一个公共的前缀
    #ignoredServices: '*'
  routes:
    api-a:
      path: /api-a/** #匹配/api-a/** 均路由到cloud-client,默认该值为serviceId（就是注册服务的名称，属性spring.application.name）
      serviceId: service-ribbon  #指定路由到的serviceId
    api-b:
      path: /api-b/**
      serviceId: service-feign
  #是否开启重试功能
  retryable: true
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  #对当前服务的重试次数
ribbon:
  MaxAutoRetries: 2
  #切换相同Server的次数
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000